import BigNumber from 'bignumber.js';

export function numberToText(number) {
  const scaleNames = [
    '',
    'thousand',
    'million',
    'billion',
    'trillion',
    'quadrillion',
    'quintillion',
    'sextillion',
    'septillion',
    'octillion',
    'nonillion',
    'decillion',
    'undecillion',
    'duodecillion',
    'tredecillion',
    'quattuordecillion',
    'quindecillion',
    'sexdecillion',
    'septendecillion',
    'octodecillion',
    'novemdecillion',
    'vigintillion',
    'unvigintillion',
    'duovigintillion',
    'trevigintillion',
    'quattuorvigintillion',
    'quinvigintillion',
    'sexvigintillion',
    'septenvigintillion',
    'octovigintillion',
    'novemvigintillion',
    'trigintillion',
    'untrigintillion',
    'duotrigintillion',
    'tretrigintillion',
    'quattuortrigintillion',
    'quintrigintillion',
    'sextrigintillion',
    'septentrigintillion',
    'octotrigintillion',
    'novemtrigintillion',
    'quadragintillion',
    'unquadragintillion',
    'duoquadragintillion',
    'trequadragintillion',
    'quattuorquadragintillion',
    'quinquadragintillion',
    'sexquadragintillion',
    'septenquadragintillion',
    'octoquadragintillion',
    'novemquadragintillion',
    'quinquagintillion',
    'unquinquagintillion',
    'duoquinquagintillion',
    'trequinquagintillion',
    'quattuorquinquagintillion',
    'quinquinquagintillion',
    'sexquinquagintillion',
    'septenquinquagintillion',
    'octoquinquagintillion',
    'novemquinquagintillion',
    'sexagintillion',
    'unsexagintillion',
    'duosexagintillion',
    'tresexagintillion',
    'quattuorsexagintillion',
    'quinsexagintillion',
    'sexsexagintillion',
    'septensexagintillion',
    'octosexagintillion',
    'novemsexagintillion',
    'septuagintillion',
    'unseptuagintillion',
    'duoseptuagintillion',
    'treseptuagintillion',
    'quattuorseptuagintillion',
    'quinseptuagintillion',
    'sexseptuagintillion',
    'septenseptuagintillion',
    'octoseptuagintillion',
    'novemseptuagintillion',
    'octogintillion',
    'unoctogintillion',
    'duooctogintillion',
    'treoctogintillion',
    'quattuoroctogintillion',
    'quinoctogintillion',
    'sexoctogintillion',
    'septenoctogintillion',
    'octooctogintillion',
    'novemoctogintillion',
    'nonagintillion',
    'unnonagintillion',
    'duononagintillion',
    'trenonagintillion',
    'quattuornonagintillion',
    'quinnonagintillion',
    'sexnonagintillion',
    'septennonagintillion',
    'octononagintillion',
    'novemnonagintillion',
    'centillion',
  ];

  const numObj = new BigNumber(number);
  const scaleIndex = Math.floor(numObj.e / 3);
  const scaleName = scaleNames[scaleIndex];

  const roundedResult = numObj
    .dividedBy(BigNumber(10).pow(scaleIndex * 3))
    .toNumber();

  return `${roundedResult} ${scaleName}`;
}
